<a href="https://colab.research.google.com/github/UzochiE/jupyterlab/blob/main/Copy_of_Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)


TensorFlow version: 2.12.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.04252706, -0.5739717 , -0.04039516, -0.21607861, -0.16825019,
        -0.7954096 , -0.29435787,  0.33459896,  1.6299987 ,  0.05521613]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.07436506, 0.04370845, 0.07452376, 0.06251675, 0.06557949,
        0.03502645, 0.05780962, 0.1084308 , 0.39603868, 0.08200082]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

3.3516517

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.3018 - accuracy: 0.9117
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1469 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1104 - accuracy: 0.9663
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0893 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0768 - accuracy: 0.9762


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0738 - accuracy: 0.9767 - 800ms/epoch - 3ms/step


[0.07384347170591354, 0.9767000079154968]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.46715715e-08, 4.64218850e-08, 1.08807899e-06, 7.16117720e-05,
        8.72987793e-11, 4.03317443e-07, 4.11690213e-12, 9.99898314e-01,
        6.71039345e-07, 2.77997151e-05],
       [1.99980099e-09, 9.40566133e-06, 9.99982834e-01, 6.93429502e-06,
        4.88519984e-15, 6.86536126e-08, 2.66709188e-09, 6.99388464e-11,
        7.24766835e-07, 1.44425108e-13],
       [5.14520309e-07, 9.99634981e-01, 1.55279922e-05, 2.86147247e-06,
        9.31731483e-06, 2.14235070e-06, 4.93221432e-06, 2.88342009e-04,
        4.11779583e-05, 1.91311827e-07],
       [9.99490857e-01, 1.49461776e-08, 7.54352368e-05, 1.56039118e-06,
        6.30359818e-06, 4.60449792e-06, 3.06178321e-04, 6.58850040e-05,
        1.27016165e-06, 4.78291186e-05],
       [1.75354069e-06, 1.19692944e-09, 2.96750204e-05, 6.31106056e-09,
        9.98879373e-01, 3.49961589e-08, 3.21667727e-07, 1.08035965e-05,
        4.39839778e-06, 1.07361481e-03]], dtype=float32)>